version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092-9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  fdb:
    image: foundationdb/foundationdb:5.2.5
    ports:
      - "4500:4500"
    environment:
      FDB_CLUSTER_FILE_CONTENTS: docker:docker@192.168.99.100:4500
      FDB_COORDINATOR: 192.168.99.100:4500

