version: '3.3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${CAELUM_DOCKER_HOST}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  fdb:
    image: foundationdb/foundationdb:6.2.22
    network_mode: "host"
    ports:
      - "4500:4500"
    command: [ "/bin/sh", "-c", "echo docker:docker@${CAELUM_DOCKER_HOST}:4500 > /var/fdb/fdb.cluster && fdbserver --listen_address 0.0.0.0:4500 --public_address ${CAELUM_DOCKER_HOST}:4500 --datadir /var/fdb/data --logdir /var/fdb/logs" ]

